[package]
name = "env_samp"
version = "0.1.0"
edition = "2024"
authors = ["NullSablex"]
repository = "https://github.com/NullSablex/env_samp"
homepage = "https://github.com/NullSablex/env_samp"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
samp = { git = "https://github.com/ZOTTCE/samp-rs", rev = "17ecb2f722bf0d74a98eb782745cd77e41c3c60a" }
log = "0.4"
