[package]
name = "env_samp"
version = "1.0.0"
edition = "2024"
authors = ["NullSablex"]
repository = "https://github.com/NullSablex/env-samp"
homepage = "https://github.com/NullSablex/env-samp"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
samp = { git = "https://github.com/NullSablex/rust-samp.git", tag = "v3.0.0" }
chrono = "0.4"

[package.metadata.samp]
uid = "0xda6b28e7df4a9f5f"